---
engines:
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "app/**.sass"
    - "app/**.scss"
    - "app/**.js"
exclude_paths:
  - config/
  - coverage/
  - node_modules/
  - tests/
  - vendor/
