---
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
     - fluxbox

sudo: false

cache:
  directories:
    - $HOME/.npm

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm run test-with-coveralls

after_success:
  - npm run semantic-release

before_deploy:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET_DEV
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    branch: develop
